### PR TITLE
Update Django in release branch

### PR DESCRIPTION
**Pull request by DavidLemayian**
Currently `master` uses Django 1.11 but `releases` branch uses 1.9.

### CODE REVIEW

**Comment by knightebsuku** [comment]
@DavidLemayian 
 If I recall correctly, there was a braking change in django between 1.9 and 1.10, The way that urls are called changed. 

This is what is causing a Build Failure.
https://docs.djangoproject.com/en/2.1/releases/1.10/#features-removed-in-1-10

**Comment by DavidLemayian** [comment]
@ebsuku Just remembered that too. Thanks for flagging. I'll work on fixing.

**Comment by DavidLemayian** [comment]
@ebsuku also apologies for sending through the ping on Slack before waiting for the Travis test to finish. I was distracted. 😞  Should be all good now. 😁

**Comment by knightebsuku** [comment]
OK, I tried running an instance  of wazimap_za with pull and there are some bumps.
* The context_processors module has moved to ```django.templates``` instead of  ```django.core``` with regards to templates, this also requires a redefining of the TEMPLATES variable.

**Comment by DavidLemayian** [comment]
Fixed templates issues and tested on wazimap-za. Thanks @ebsuku .

Also, this PR needed for it to work well - 
https://github.com/OpenUpSA/wazimap-za/pull/306

**Pull request merged**
