### PR TITLE
white noise should be now added as a middleware

### PR DESCRIPTION
**Pull request by knightebsuku**
Direct wsgi integration for django has been deprecated, recommendation is to add whitenoise as middleware:

http://whitenoise.evans.io/en/stable/changelog.html#v4-0

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
@ebsuku 

Should the middleware also be added to [`settings.py`](https://github.com/OpenUpSA/wazimap/blob/63274484fbedaa4243a745d5e0441e1d903cda0b/wazimap/settings.py) in this project or would users of the Wazimap project be expected to add it to their own `settings.py`?

**Comment by knightebsuku** [comment]
I'd rather have the users add the whitenoise middleware into their own settings.py file, rather than within wazimap.

**Comment by longhotsummer** [comment]
I agree with @ebsuku -- this is a production-time deployment concern and 3rd parties may want to deploy their Wazimap instances in a different way that doesn't require whitenoise.

**Comment by cliftonmcintosh** [comment]
Thank you, @ebsuku and @longhotsummer

**Pull request merged**
