### PR TITLE
Upgrade Wazimap to Python 3

### PR DESCRIPTION
**Pull request by DavidLemayian**
Just seen #147 . Here's our candidate too for Python 3 that we're using in production.

### CODE REVIEW

**Comment by knightebsuku** [comment]
Thanks @DavidLemayian, I'll be looking into this today.

**Review by knightebsuku — COMMENTED** [review]
This looks good. I'll merge soon.

**Comment by knightebsuku** [comment]
@DavidLemayian 
I get a ```TypeError: __init__() missing 1 required positional argument: 'on_delete'``` 
This is for the Column class in wazimap/census/models.py

I guess django 2  now enforces this.

**Comment by DavidLemayian** [comment]
@ebsuku That sounds right. :)

**Comment by knightebsuku** [comment]
Also all instances of ```django.core.urlresolvers``` need to be changed to ```django.urls```

I'm busy running this pull on an instance of wazimap, thats why I'm picking these things up now.

**Comment by DavidLemayian** [comment]
cc @kilemensi

**Comment by kilemensi** [comment]
Yes @ebsuku, a few things will need to be updated for Django 2.2 since we’re still running Django 1.11 on Python 3.... the migration to Django 2.2 was next

**Pull request merged**
