### PR TITLE
Fix geo_version already exists

### PR DESCRIPTION
**Pull request by kilemensi**
By the time the add `geo_version` column migration runs, it's possible to have a table with `geo_version` column already defined. This shouldn't stop the system migration but should just inform the developers.

### CODE REVIEW

**Comment by longhotsummer** [comment]
Thanks for the suggestion. How about we make this change, which simply skips tables that already have that column -- around line 27:

```python
table = db_model.__table__   # this line already exists

cols = [c['name'] for c in inspector.get_columns(table.name)]
if 'geo_version' in cols:
    continue
```

Can you check that that solves your problem? I think it should, but I haven't had a chance to test it.

**Review by longhotsummer — CHANGES_REQUESTED** [review]
Suggested changes.

**Comment by kilemensi** [comment]
Works @longhotsummer. Updated the PR.

**Comment by longhotsummer** [comment]
Awesome, thanks!

**Pull request merged**
