### PR TITLE
Add API call to list geo children

### PR DESCRIPTION
**Pull request by DavidLemayian**
Just as we can list parents for a geo using `/api/1.0/geo/<geo_id>/parents` ..

this PR allows us to list children in the same manner `/api/1.0/geo/<geo_id>/children`

### CODE REVIEW

**Comment by knightebsuku** [comment]
Out of curiosity what is the use case?

**Comment by KhadijaMahanga** [comment]
@ebsuku We are building a site with multiple countries (continent as a root geo), so on a specific country page we want to be able to search for places below a country (or any specific geo_id) and not search our entire geography(continent).

**Comment by knightebsuku** [comment]
ahh, nice

**Review by knightebsuku — APPROVED** [review]
Looks good.

**Pull request merged**
