### PR TITLE
Point data

### PR DESCRIPTION
**Pull request by xybrnet**
WIP

### CODE REVIEW

**Review by knightebsuku — COMMENTED** [review]
We've currently being involved with a couple of projects that we looking to add point data, based on the feedback and features that they have requested, we think that its best to treat point data as an external feature to wazimap.

**Comment by DavidLemayian** [comment]
Thanks @ebsuku . Is the plan to make a `wazimap-point` package?

**Comment by knightebsuku** [comment]
@DavidLemayian 

That's correct, we'll create it as a separate django app, but specifically created to work with wazimap.

**Comment by DavidLemayian** [comment]
Excellent. Thanks @ebsuku .

Is that the same plan for `releases` or will that be merged soon?

We're happy to lend a hand wherever we can.

**Comment by knightebsuku** [comment]
So, releases is actually v2.0 of wazimap. There are some breaking changes that need to be documented but I think we are almost there. 
We are planning on merging releases so that we can move to django 1.11 and perhaps python3.
Any help would be greatly appreciated.

**Pull request closed without merging**
